version: '3'

services:
    plant-service:
        image: node:7.5.0-alpine
        volumes:
            - ./plant-service/:/usr/src/app/
        working_dir: /usr/src/app/
        command: "sh -c 'npm run watch'"
        links: 
            - mysql
        ports:
            - "3000"
        env_file: 
            - ./plant-service/.secret.db.env

    angular-client:
        image: node:7.5.0-alpine
        volumes:
            - ./angular-client/:/usr/src/app/
        working_dir: /usr/src/app/
        command: "sh -c 'npm start'"
        ports:
            - "4200"
    
    gateway:
        image: nginx:1.11.9-alpine
        ports:
            - "80:80"
            - "8080:8080"
        links:
            - angular-client
            - plant-service
            - serial-service
        depends_on:
            - angular-client
            - plant-service
            - serial-service
        volumes:
            - ./gateway/conf.d/:/etc/nginx/conf.d/:ro
    
    serial-service:
        image: arunk3001/node-serialport:4.0.7-alpine
        privileged: true
        environment: 
            - "COM_NAME"
        devices: 
            - "${COM_NAME}:${COM_NAME}"
        volumes:
            - ./serial-service/:/usr/src/app/
        working_dir: /usr/src/app/
        ports:
            - "8080"
        command: "sh -c 'COM_NAME=${COM_NAME} npm run watch'"

    mysql:
        image: arunk3001/mysql:10.1.21-alpine
        ports: 
            - "3306:3306"
            - "3306"
        volumes: 
            - ./mysql/data/:/app/
        env_file:
            - ./mysql/.secret.setup.env
